version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      API_KEY: ${API_KEY}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - cr_stats
    ports:
      - 5000:5000
    restart: always
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src
  postgresql:
    container_name: postgres
    image: postgres:13.4
    networks:
      - cr_stats
    ports:
      - 5432:5432
    restart: always
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: server
    networks:
      - cr_stats
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./frontend/build:/var/www/html
      - ./server/default.conf:/etc/nginx/sites-available/default
      - ./server/options-ssl-nginx.conf:/etc/letsencrypt/options-ssl-nginx.conf
      - ./server/fullchain.pem:/etc/letsencrypt/live/cr.matthewmyoung.com/fullchain.pem
networks:
  cr_stats:
    driver: bridge
    name: cr_stats
volumes:
  postgres_data: