"""Curated card name -> type (building / spell / troop) mapping.

The Clash Royale API does not expose a card's category (building/spell/troop),
so it is maintained here by hand. Keys must match `cards.name` exactly. When
Supercell adds cards, add them here; `card_type()` returns None for anything
missing so unknown cards simply won't match a type filter (rather than being
silently mislabeled).
"""

BUILDING = "building"
SPELL = "spell"
TROOP = "troop"

CARD_TYPES = {
    # Champions (all troops)
    "Archer Queen": TROOP,
    "Boss Bandit": TROOP,
    "Goblinstein": TROOP,
    "Golden Knight": TROOP,
    "Little Prince": TROOP,
    "Mighty Miner": TROOP,
    "Monk": TROOP,
    "Skeleton King": TROOP,
    # Common
    "Archers": TROOP,
    "Arrows": SPELL,
    "Barbarians": TROOP,
    "Bats": TROOP,
    "Berserker": TROOP,
    "Bomber": TROOP,
    "Cannon": BUILDING,
    "Electro Spirit": TROOP,
    "Elite Barbarians": TROOP,
    "Firecracker": TROOP,
    "Fire Spirit": TROOP,
    "Giant Snowball": SPELL,
    "Goblin Gang": TROOP,
    "Goblins": TROOP,
    "Ice Spirit": TROOP,
    "Knight": TROOP,
    "Minion Horde": TROOP,
    "Minions": TROOP,
    "Mortar": BUILDING,
    "Rascals": TROOP,
    "Royal Delivery": SPELL,
    "Royal Giant": TROOP,
    "Royal Recruits": TROOP,
    "Skeleton Barrel": TROOP,
    "Skeleton Dragons": TROOP,
    "Skeletons": TROOP,
    "Spear Goblins": TROOP,
    "Tesla": BUILDING,
    "Zap": SPELL,
    # Epic
    "Baby Dragon": TROOP,
    "Balloon": TROOP,
    "Barbarian Barrel": SPELL,
    "Bowler": TROOP,
    "Cannon Cart": TROOP,
    "Clone": SPELL,
    "Dark Prince": TROOP,
    "Electro Dragon": TROOP,
    "Electro Giant": TROOP,
    "Executioner": TROOP,
    "Freeze": SPELL,
    "Giant Skeleton": TROOP,
    "Goblin Barrel": SPELL,
    "Goblin Curse": SPELL,
    "Goblin Drill": BUILDING,
    "Goblin Giant": TROOP,
    "Golem": TROOP,
    "Guards": TROOP,
    "Hunter": TROOP,
    "Lightning": SPELL,
    "Mirror": SPELL,
    "P.E.K.K.A": TROOP,
    "Poison": SPELL,
    "Prince": TROOP,
    "Rage": SPELL,
    "Rune Giant": TROOP,
    "Skeleton Army": TROOP,
    "Tornado": SPELL,
    "Vines": SPELL,
    "Void": SPELL,
    "Wall Breakers": TROOP,
    "Witch": TROOP,
    "X-Bow": BUILDING,
    # Legendary
    "Bandit": TROOP,
    "Electro Wizard": TROOP,
    "Fisherman": TROOP,
    "Goblin Machine": TROOP,
    "Graveyard": SPELL,
    "Ice Wizard": TROOP,
    "Inferno Dragon": TROOP,
    "Lava Hound": TROOP,
    "Lumberjack": TROOP,
    "Magic Archer": TROOP,
    "Mega Knight": TROOP,
    "Miner": TROOP,
    "Mother Witch": TROOP,
    "Night Witch": TROOP,
    "Phoenix": TROOP,
    "Princess": TROOP,
    "Ram Rider": TROOP,
    "Royal Ghost": TROOP,
    "Sparky": TROOP,
    "Spirit Empress": TROOP,
    "The Log": SPELL,
    # Rare
    "Barbarian Hut": BUILDING,
    "Battle Healer": TROOP,
    "Battle Ram": TROOP,
    "Bomb Tower": BUILDING,
    "Dart Goblin": TROOP,
    "Earthquake": SPELL,
    "Elixir Collector": BUILDING,
    "Elixir Golem": TROOP,
    "Fireball": SPELL,
    "Flying Machine": TROOP,
    "Furnace": TROOP,
    "Giant": TROOP,
    "Goblin Cage": BUILDING,
    "Goblin Demolisher": TROOP,
    "Goblin Hut": BUILDING,
    "Heal Spirit": TROOP,
    "Hog Rider": TROOP,
    "Ice Golem": TROOP,
    "Inferno Tower": BUILDING,
    "Mega Minion": TROOP,
    "Mini P.E.K.K.A": TROOP,
    "Musketeer": TROOP,
    "Rocket": SPELL,
    "Royal Hogs": TROOP,
    "Suspicious Bush": TROOP,
    "Three Musketeers": TROOP,
    "Tombstone": BUILDING,
    "Valkyrie": TROOP,
    "Wizard": TROOP,
    "Zappies": TROOP,
}


def card_type(name):
    """Return 'building' | 'spell' | 'troop' for a card name, or None."""
    return CARD_TYPES.get(name)
